# Generated by Django 5.0.6 on 2024-08-11 14:16

from django.db import migrations, models



def add_courses(apps, schema_editor):
    Course = apps.get_model('your_app_name', 'Course')
    courses = [
        {"course_code": "ENG101", "course_title": "Introduction to Engineering", "credit_load": 3},
        {"course_code": "ENG102", "course_title": "Engineering Mathematics I", "credit_load": 3},
        {"course_code": "ENG103", "course_title": "Physics for Engineers", "credit_load": 4},
        {"course_code": "ENG104", "course_title": "Engineering Drawing", "credit_load": 2},
        {"course_code": "ENG201", "course_title": "Engineering Mathematics II", "credit_load": 3},
        {"course_code": "ENG202", "course_title": "Thermodynamics", "credit_load": 3},
        {"course_code": "ENG203", "course_title": "Mechanics of Materials", "credit_load": 3},
        {"course_code": "ENG204", "course_title": "Fluid Mechanics", "credit_load": 3},
        {"course_code": "ENG301", "course_title": "Electrical Engineering", "credit_load": 3},
        {"course_code": "ENG302", "course_title": "Control Systems", "credit_load": 3},
        {"course_code": "ENG303", "course_title": "Heat Transfer", "credit_load": 3},
        {"course_code": "ENG304", "course_title": "Engineering Design", "credit_load": 3},
        {"course_code": "ENG401", "course_title": "Engineering Project", "credit_load": 6},
        {"course_code": "ENG402", "course_title": "Environmental Engineering", "credit_load": 3},
        {"course_code": "ENG403", "course_title": "Manufacturing Processes", "credit_load": 3},
        {"course_code": "ENG404", "course_title": "Engineering Management", "credit_load": 3},
        {"course_code": "ENG405", "course_title": "Capstone Design Project", "credit_load": 6},
        # Add more courses as needed
    ]

    for course in courses:
        Course.objects.create(**course)



class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_course_courseregistration_total_credit_load_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RunPython(add_courses),
    ]
