# Generated by Django 5.0.6 on 2024-08-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('credit_load', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='total_credit_load',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_year_of_study',
            field=models.IntegerField(default='2024'),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='courses',
            field=models.ManyToManyField(to='students.course'),
        ),
    ]
